-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 11:22:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Inserator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Inserator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Inserator` DEFAULT CHARACTER SET utf8 ;
USE `Inserator` ;

-- -----------------------------------------------------
-- Table `Inserator`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inserator`.`user` ;

CREATE TABLE IF NOT EXISTS `Inserator`.`user` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `User_Firstname` VARCHAR(20) NOT NULL,
  `User_Name` VARCHAR(20) NOT NULL,
  `User_Username` VARCHAR(20) NOT NULL,
  `User_Email` VARCHAR(50) NOT NULL,
  `User_Phone` VARCHAR(20) NOT NULL,
  `User_PWD` CHAR(60) NOT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inserator`.`inserate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inserator`.`inserate` ;

CREATE TABLE IF NOT EXISTS `Inserator`.`inserate` (
  `Inserat_ID` INT NOT NULL AUTO_INCREMENT,
  `Inserat_Name` VARCHAR(50) NOT NULL,
  `Inserat_Typ` VARCHAR(45) NOT NULL,
  `Inserat_Description` LONGTEXT NOT NULL,
  `Inserat_Location` VARCHAR(50) NOT NULL,
  `Inserat_Email` VARCHAR(50) NOT NULL,
  `Inserat_Phone` VARCHAR(20) NOT NULL,
  `Inserat_Date` DATETIME NOT NULL,
  `Inserat_User_ID` INT NOT NULL,
  `Inserat_IsActive` TINYINT NOT NULL,
  PRIMARY KEY (`Inserat_ID`),
  INDEX `fk_Inserate_User_idx` (`Inserat_User_ID` ASC),
  CONSTRAINT `fk_Inserate_User`
    FOREIGN KEY (`Inserat_User_ID`)
    REFERENCES `Inserator`.`user` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Inserator` ;

-- -----------------------------------------------------
-- Placeholder table for view `Inserator`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inserator`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `Inserator`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `Inserator`.`view1` ;
DROP TABLE IF EXISTS `Inserator`.`view1`;
USE `Inserator`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
