-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 12:21:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Inserator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Inserator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Inserator` DEFAULT CHARACTER SET utf8 ;
USE `Inserator` ;

-- -----------------------------------------------------
-- Table `Inserator`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inserator`.`user` ;

CREATE TABLE IF NOT EXISTS `Inserator`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `pwd` CHAR(60) NOT NULL,
  `is_admin` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inserator`.`inserat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inserator`.`inserat` ;

CREATE TABLE IF NOT EXISTS `Inserator`.`inserat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `location` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `date` DATETIME NOT NULL,
  `is_active` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inserate_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_inserate_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Inserator`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Inserator` ;

-- -----------------------------------------------------
-- Placeholder table for view `Inserator`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inserator`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `Inserator`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `Inserator`.`view1` ;
DROP TABLE IF EXISTS `Inserator`.`view1`;
USE `Inserator`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
